# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.2

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/vue-tour

    branches:
      only:
        - master

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # install Cypress dependencies
      - run: sudo apt-get update && sudo apt-get install -y libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb

      - run: npm install
      - run: npm rebuild node-sass

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run test
      - run: npm run build

      - run: cd ./demo/ && npm install

      - save_cache:
          paths:
            - demo/node_modules
          key: v1-dependencies-{{ checksum "demo/package.json" }}

      - run:
          command: cd ./demo/ && npm run serve
          background: true

      # wait for the webserver to be started in a little hacky way
      - run: sleep 5

      # run tests!
      - run: cd ./demo/ && npm run test:e2e -- --headless
      - run: cd ./demo/ && npm run build

      - run: rm -rf ./docs/
      - run: mv ./demo/dist/ ./docs/
      - run: cp ./public/demo.html ./dist

      - run: git status
